name: Build and Publish Library
on:
  workflow_call:
    inputs:
      build_path:
        description: 'Path to the library to build'
        required: false
        default: 'dist/libs'
        type: string
      package_path:
        description: 'Path to the package.json directory'
        required: false
        default: './'
        type: string
    secrets:
      NPM_TOKEN:
        required: true
jobs:
  check-package:
    runs-on: ubuntu-latest
    container: node:22
    permissions:
      packages: write
      contents: read
    outputs:
      packageExists: ${{ steps.check.outputs.packageExists }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: |
          cd ${{ inputs.package_path }}
          npm install
      - name: Check if package is published
        run: |
          cd ${{ inputs.package_path }}
          if [ "$(npm view $(node -p "require('./package.json').name")@$(node -p "require('./package.json').version") version)" = "$(node -p "require('./package.json').version")" ]; then
            echo "packageExists=True" >> $GITHUB_OUTPUT
          else
            echo "packageExists=False" >> $GITHUB_OUTPUT
          fi
        id: check
  build:
    needs: check-package
    container: node:22
    if: ${{ needs.check-package.outputs.packageExists == 'False' }}
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd ${{ inputs.package_path }}
          npm install
      - run: |
          cd ${{ inputs.package_path }}
          npm run build
      - run: |
          cd ${{ inputs.package_path }}
          export CURRENT_PATH=$(pwd)
          IFS=';' read -ra ADDR <<< "${{ inputs.build_path }}"
          for i in "${ADDR[@]}"; do
            cd $CURRENT_PATH/$i && npm publish --access public
          done
        shell: bash
